query {
	user(login: "${user}") {
		pinnedItems(types: [REPOSITORY], first: 6) {
			nodes {
				... on Repository {
					id
					name
					description
					url
					forkCount
					stargazerCount
					languages(first: 5) {
						nodes {
							... on Language {
								name
							}
						}
					}
				}
			}
		}
	}
}
